print_array1:	print_array.o \
		ex_print_array_main.o
	gcc -o $@ $^

print_array_wrong:	print_array.o \
			ex_print_array_wrong_main.o
	gcc -o $@ $^

print_array2:	print_array.o \
		print_array_main2.o
	gcc -o $@ $^
