all	:	bubble_sort selection_sort insertion_sort

bubble_sort:	sort_main.o \
		bubble_sort.c
	gcc -o $@ $^

selection_sort:	sort_main.o \
		selection_sort.c
	gcc -o $@ $^

insertion_sort:	sort_main.o \
		insertion_sort.c
	gcc -o $@ $^

